services:
  n8n:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: n8n
    ports:
      - "5678:5678"
    env_file:
      - .env
    environment:
      - DB_TYPE=${DB_TYPE:-postgresdb}
      - DB_POSTGRESDB_HOST=${DB_HOST:-postgres}
      - DB_POSTGRESDB_PORT=${DB_PORT:-5432}
      - DB_POSTGRESDB_DATABASE=${DB_DATABASE:-n8n}
      - DB_POSTGRESDB_USER=${DB_USER:-n8n}
      - DB_POSTGRESDB_PASSWORD=${DB_PASSWORD:-s3cr3t}
      - N8N_BASIC_AUTH_ACTIVE=false
      - N8N_HOST=localhost
      - N8N_PORT=${N8N_PORT:-5678}
      - NODE_ENV=${ENV}
      - GENERIC_TIMEZONE=${N8N_TIMEZONE:-America/Mexico_City}
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY:-s3cr3t}
      - N8N_CUSTOM_EXTENSIONS=/data/custom-nodes
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:13
    container_name: postgres
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_DATABASE:-n8n}
      - POSTGRES_USER=${DB_USER:-n8n}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-s3cr3t}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - "8710:5432"

volumes:
  n8n_data:
  postgres_data:
